version: '3.9'
services:
  mysql:
    container_name: mysql
    platform: linux/x86_64
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'pass'
      MYSQL_ROOT_PASSWORD: 'pass'
      MYSQL_DATABASE: 'db'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - dbdata:/var/lib/mysql
  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_SOURCE=user:pass@tcp(mysql:3306)/db?parseTime=true
    depends_on:
      - mysql
volumes:
  dbdata:
