// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"time"
)

type Account struct {
	ID        int64
	Balance   int64
	CreatedAt time.Time
	UpdatedAt time.Time
}

type Transaction struct {
	ID        int64
	FromID    int64
	ToID      int64
	Amount    int64
	CreatedAt time.Time
}
